Added Update Plugin functionality
Please note this code was copied from the Matrix Message code, I think it is setup correctly however I can't test it fully because it states this in the update_plugin.log:

Thu May 26 20:51:14 PDT 2016
Updating plugin Twitter
error: Your local changes to the following files would be overwritten by merge:
	plugin_setup.php
Please, commit your changes or stash them before you can merge.
Aborting
Updating 6c3dc13..0dd9fa3

This leads me to believe it's connecting successfully, it just doesn't want to overwrite my updated file.